/** Autogenerated from markdown files using mdx-parser deno script */
import React from 'react';
import { Paper } from '@material-ui/core';
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { themeSelector } from '@state/theme.state';

const HomePageView = () => {
  const theme = useSelector(themeSelector);

  return (
    <div>
      <Paper
        elevation={0}
        className="mt-8"
        style={{ backgroundColor: theme.body.bg, color: theme.body.text }}
      >
        <div className="flex row justify-between items-center mb-2">
          <Link to="/articles/demystifying-javascript-closures">
            <h3 className="mt-0 hover:underline">
              Demystifying JavaScript Closures
            </h3>
          </Link>
          <p className="text-lg my-0">10 mins</p>
        </div>
        <div className="flex row items-center">
          <span className="date-tag">7th Nov, 2020</span>
          <span className="article-tags" style={{ backgroundColor: theme.tag }}>
            JavaScript
          </span>
          <span className="article-tags" style={{ backgroundColor: theme.tag }}>
            Theory
          </span>
        </div>
      </Paper>

      <Paper
        elevation={0}
        className="mt-8"
        style={{ backgroundColor: theme.body.bg, color: theme.body.text }}
      >
        <div className="flex row justify-between items-center mb-2">
          <Link to="/articles/devlauncher-hackathon-experience">
            <h3 className="mt-0 hover:underline">
              5 Takeaways From My First Hackathon Experience
            </h3>
          </Link>
          <p className="text-lg my-0">7 mins</p>
        </div>
        <div className="flex row items-center">
          <span className="date-tag">9th Nov, 2020</span>
          <span className="article-tags" style={{ backgroundColor: theme.tag }}>
            Hackathon
          </span>
          <span className="article-tags" style={{ backgroundColor: theme.tag }}>
            Takeaways
          </span>
        </div>
      </Paper>
    </div>
  );
};

export default HomePageView;
