/** Autogenerated from markdown files using mdx-parser deno script */
import React from 'react';
import { Paper } from '@material-ui/core';
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { themeSelector } from '@state/theme.state';
import { clientSelector, DEVICE } from '@state/client.state';

const HomePageView = () => {
  const theme = useSelector(themeSelector);
  const client = useSelector(clientSelector);

  const isMobile = client.device === DEVICE.MOBILE;

  return (
    <div>
      <Paper
        elevation={0}
        className="mt-8"
        style={{ backgroundColor: theme.body.bg, color: theme.body.text }}
      >
        <div
          className={`flex ${
            isMobile ? 'flex-col' : 'flex-row justify-between items-center'
          } mb-2`}
        >
          <Link to="/articles/introduction-to-rxjs">
            <h3
              className={`mt-0 hover:underline ${isMobile ? 'text-2xl' : ''}`}
            >
              Introduction to RxJS
            </h3>
          </Link>
          {!isMobile && <p className="text-lg my-0">10 mins</p>}
        </div>
        <div className="flex row items-center flex-wrap w-full">
          <div className="date-tag">30th Nov, 2020</div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            Angular
          </div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            RxJS
          </div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            Theory
          </div>
        </div>
      </Paper>

      <Paper
        elevation={0}
        className="mt-8"
        style={{ backgroundColor: theme.body.bg, color: theme.body.text }}
      >
        <div
          className={`flex ${
            isMobile ? 'flex-col' : 'flex-row justify-between items-center'
          } mb-2`}
        >
          <Link to="/articles/devlauncher-hackathon-experience">
            <h3
              className={`mt-0 hover:underline ${isMobile ? 'text-2xl' : ''}`}
            >
              5 Takeaways From My First Hackathon Experience
            </h3>
          </Link>
          {!isMobile && <p className="text-lg my-0">10 mins</p>}
        </div>
        <div className="flex row items-center flex-wrap w-full">
          <div className="date-tag">9th Nov, 2020</div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            Hackathon
          </div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            Takeaways
          </div>
        </div>
      </Paper>

      <Paper
        elevation={0}
        className="mt-8"
        style={{ backgroundColor: theme.body.bg, color: theme.body.text }}
      >
        <div
          className={`flex ${
            isMobile ? 'flex-col' : 'flex-row justify-between items-center'
          } mb-2`}
        >
          <Link to="/articles/demystifying-javascript-closures">
            <h3
              className={`mt-0 hover:underline ${isMobile ? 'text-2xl' : ''}`}
            >
              Demystifying JavaScript Closures
            </h3>
          </Link>
          {!isMobile && <p className="text-lg my-0">10 mins</p>}
        </div>
        <div className="flex row items-center flex-wrap w-full">
          <div className="date-tag">7th Nov, 2020</div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            JavaScript
          </div>
          <div className="article-tags" style={{ backgroundColor: theme.tag }}>
            Theory
          </div>
        </div>
      </Paper>
    </div>
  );
};

export default HomePageView;
