/** Autogenerated from markdown files using mdx-parser deno script */
import React from 'react';
import { Paper } from '@material-ui/core';
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { themeSelector } from '@state/theme.state';

const HomePageView = () => {
  const theme = useSelector(themeSelector);
  
  return (
    <div>
        <Link to="/articles/demystifying-javascript-closures"><Paper elevation={0} className="p-4 mt-8 cursor-pointer" style={{ backgroundColor: theme.elevated.bg, color: theme.elevated.text }}>
        <div className="flex row justify-between items-center">
        
        <h2 className="text-2xl font-semibold mt-0">Demystifying JavaScript Closures</h2>
          <p className="text-lg my-0">7th November, 2020</p>
          </div>
          <p>Test Description</p>
        </Paper></Link>
        
        <Link to="/articles/intro-to-rxjs"><Paper elevation={0} className="p-4 mt-8 cursor-pointer" style={{ backgroundColor: theme.elevated.bg, color: theme.elevated.text }}>
        <div className="flex row justify-between items-center">
        
        <h2 className="text-2xl font-semibold mt-0">Introduction to RxJS</h2>
          <p className="text-lg my-0">7th November, 2020</p>
          </div>
          <p>Test Description</p>
        </Paper></Link>
            </div>
  );
};

export default HomePageView;
